name: Pipeline for Publish Docker image

on:
  push:
    branches: [master]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          gradle-version: 6.4
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/github-repo-0.0.1-SNAPSHOT.jar
      - name: Docker Build and Publish
        run: |
            ls -R
            pwd
            docker login https://docker.pkg.github.com -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -f Dockerfile.grdl -t docker.pkg.github.com/adityapratapbhuyan/spring-rest-demo:latest .
            docker images  docker.pkg.github.com/adityapratapbhuyan/spring-rest-demo:latest
            docker push
      - name: build-docker-image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.grdl
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: aditya-bhuyan/docker-images/spring-rest-demo
          tag_with_ref: true
